# Generated by Django 4.0.5 on 2022-06-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameGoods', models.CharField(max_length=255)),
                ('TypeGoods', models.CharField(max_length=255)),
                ('DateDeliv', models.DateField(auto_now=True)),
                ('AddressDeliv', models.CharField(max_length=255)),
            ],
        ),
    ]
