# Generated by Django 4.0.5 on 2022-06-20 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dform', '0002_deliv_file_alter_deliv_datedeliv_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliv',
            name='AddressDeliv',
        ),
    ]
