# Generated by Django 4.0.5 on 2022-06-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dform', '0003_remove_deliv_addressdeliv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliv',
            name='DateDeliv',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliv',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='File address'),
        ),
    ]
